#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
  - docker-compose
  - git
  - ufw
  - telnet

runcmd:
  - sudo systemctl start docker
  - sudo systemctl enable docker
